/**
 * Mock Data - Central de Projetos NIE
 * Dados simulados para desenvolvimento frontend
 */

import { User, Project, UserProfile } from '@/types';

// ============================================
// ANO ATUAL DINÂMICO
// ============================================

export const CURRENT_YEAR = new Date().getFullYear();
export const NEXT_YEAR = CURRENT_YEAR + 1;

// ============================================
// USERS (Mock Database)
// ============================================

export const MOCK_USERS: User[] = [
  // Global Admins
  {
    id: 'usr-001',
    email: 'admin@addvalora.com',
    name: 'Administrador NIE',
    profile: 'admin',
    role: 'adm-nie',
    status: 'ativo',
    cargo: 'ADM NIE',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    createdAt: `${CURRENT_YEAR}-01-15T10:00:00Z`,
    lastLogin: new Date().toISOString(),
  },
  {
    id: 'usr-ceo-1',
    email: 'lhey@addvaloraglobal.com',
    name: 'Luciana Hey',
    profile: 'executivo',
    role: 'executivo-luciana',
    status: 'ativo',
    cargo: 'Luciana',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lhey',
    createdAt: `${CURRENT_YEAR}-01-01T00:00:00Z`,
    lastLogin: new Date().toISOString(),
  },
  {
    id: 'usr-ceo-2',
    email: 'wfernandez@addvaloraglobal.com',
    name: 'William Fernandez',
    profile: 'executivo',
    role: 'executivo-william',
    status: 'ativo',
    cargo: 'William Fernandez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=wfernandez',
    createdAt: `${CURRENT_YEAR}-01-01T00:00:00Z`,
    lastLogin: new Date().toISOString(),
  },
  
];

// Senhas mock (em produção seria hash)
export const MOCK_PASSWORDS: Record<string, string> = {
  'master@addvalora.com': 'Master@2026',
  'admin@addvalora.com': 'Admin@2026',
  'lhey@addvaloraglobal.com': 'COO@2026',
  'wfernandez@addvaloraglobal.com': 'CEO@2026',
};

// ============================================
// PROJECTS - Separados em Painéis e Projetos
// ============================================

export const MOCK_PROJECTS: Project[] = [
  // ============================================
  // PAINÉIS - Apenas 4 painéis com links ativos
  // ============================================
  {
    id: 'painel-001',
    nome: 'Painel de Controle de Prazos',
    descricao: 'Sistema de gestão e monitoramento de prazos processuais e administrativos com alertas automáticos e dashboard intuitivo.',
    categoria: 'tecnologia',
    status: 'ativo',
    tipo: 'painel',
    diretoria: 'Garantia / Fiança / Riscos',
    responsavel: 'Equipe NIE',
    link: 'https://nie-prazos.pages.dev/',
    destaque: false,
    favorito: false,
    dataInicio: `${CURRENT_YEAR}-01-01`,
    dataFim: `${CURRENT_YEAR}-12-31`,
    createdAt: `${CURRENT_YEAR}-01-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-15T10:00:00Z`,
  },
  {
    id: 'painel-002',
    nome: 'Painel de Acionamentos',
    descricao: 'Plataforma de gerenciamento de acionamentos e demandas internas com acompanhamento em tempo real e relatórios gerenciais.',
    categoria: 'operacional',
    status: 'ativo',
    tipo: 'painel',
    diretoria: 'Responsabilidade Civil Geral (RCG)',
    responsavel: 'Equipe NIE',
    link: 'https://painel.nie-inteligencia.com',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-01-01`,
    dataFim: `${CURRENT_YEAR}-12-31`,
    createdAt: `${CURRENT_YEAR}-01-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-15T10:00:00Z`,
  },
  {
    id: 'painel-003',
    nome: 'Painel - SLA',
    descricao: 'Organização interna da documentação referente às SLAs das Seguradoras. Melhoria do acesso às informações sobre regras estabelecidas pelas Seguradoras.',
    categoria: 'operacional',
    status: 'ativo',
    tipo: 'painel',
    diretoria: 'Garantia / Fiança / Riscos',
    responsavel: 'NIE - Núcleo de Inteligência Estratégica',
    link: 'https://projeto-nieteste.vercel.app/',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-01-01`,
    dataFim: `${CURRENT_YEAR}-12-31`,
    createdAt: `${CURRENT_YEAR}-01-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-15T10:00:00Z`,
  },
  {
    id: 'painel-004',
    nome: 'Painel - Instituto',
    descricao: 'Organização interna da documentação referente ao Instituto Addvalora. Melhoria do acesso aos materiais de estudo interno.',
    categoria: 'rh',
    status: 'ativo',
    tipo: 'painel',
    diretoria: 'Garantia / Fiança / Riscos',
    responsavel: 'NIE - Núcleo de Inteligência Estratégica',
    link: 'https://instituto-addvalora-nie.vercel.app/',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-01-01`,
    dataFim: `${CURRENT_YEAR}-12-31`,
    createdAt: `${CURRENT_YEAR}-01-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-15T10:00:00Z`,
  },
  // ============================================
  // PROJETOS - Roadmap/Produtos em evolução
  // ============================================
  // NOTA: Projetos duplicados removidos (proj-029, proj-030, proj-031)
  // Painel - SLA e Painel - Instituto agora são apenas painéis (painel-003, painel-004)
  // Projeto 25 renomeado para evitar confusão com Painel de Acionamentos
  {
    id: 'proj-002',
    nome: 'Sistema de Gestão de Sinistros de Engenharia',
    descricao: 'Desenvolvimento de fluxo especializado para regulação de sinistros de riscos de engenharia e montagem.',
    categoria: 'operacional',
    status: 'ativo',
    tipo: 'projeto',
    diretoria: 'Property / Construção',
    responsavel: 'Paulo Cardoso - Property',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-04-15`,
    createdAt: `${CURRENT_YEAR}-04-15T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-003',
    nome: 'Portal de Clientes - Linhas Financeiras',
    descricao: 'Plataforma para acompanhamento de processos de D&O e E&O para segurados e corretores.',
    categoria: 'tecnologia',
    status: 'planejamento',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Profissional (RCP)',
    responsavel: 'Everton - RCP Brasil',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-11-01`,
    createdAt: `${CURRENT_YEAR}-11-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-004',
    nome: 'Módulo de Integração Bancária',
    descricao: 'Automação de fluxos de pagamento e conciliação bancária para a diretoria financeira.',
    categoria: 'financeiro',
    status: 'ativo',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Profissional (RCP)',
    responsavel: 'Max - CFO Brasil',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-05-20`,
    createdAt: `${CURRENT_YEAR}-05-20T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  // Projetos da Planilha NIE (adicionados automaticamente)
  {
    id: 'proj-005',
    nome: 'Automação de Garantia',
    descricao: 'Script automatizado que cria relatório diário de pendências de e-mails, consolidando informações em planilha Google Sheets. Foco em e-mails não respondidos de caixas departamentais.',
    categoria: 'tecnologia',
    status: 'ativo',
    tipo: 'projeto',
    diretoria: 'Garantia / Fiança / Riscos',
    responsavel: 'Rebeca Hilcko - Garantia',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-01-15`,
    createdAt: `${CURRENT_YEAR}-01-15T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-006',
    nome: 'Automação Robô HDI',
    descricao: 'Robô identifica e-mails "HDI SEGUROS Mensagem - N° do sinistro" e redireciona automaticamente para caixa departamental, eliminando triagem manual.',
    categoria: 'tecnologia',
    status: 'ativo',
    tipo: 'projeto',
    diretoria: 'Property / Transportes / Mecânica / Elétrica',
    responsavel: 'Clark Pellegrino - Property',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-02-01`,
    createdAt: `${CURRENT_YEAR}-02-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-007',
    nome: 'Automação Email Brasil',
    descricao: 'Solução com IA, AppScript e Google Sheets para envio automático de e-mails de acionamentos e alimentação automática de planilha de controle.',
    categoria: 'tecnologia',
    status: 'ativo',
    tipo: 'projeto',
    diretoria: 'Garantia / Fiança / Riscos',
    responsavel: 'NIE - Núcleo de Inteligência Estratégica',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-03-01`,
    createdAt: `${CURRENT_YEAR}-03-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-008',
    nome: 'Automação de Solicitações de Email/Acessos',
    descricao: 'Robô via Apps Script operando 24h que identifica solicitações de código de acesso por e-mail, registra em planilha e distribui informações automaticamente.',
    categoria: 'tecnologia',
    status: 'concluido',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Geral (RCG)',
    responsavel: 'Luciana Hey',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-01-01`,
    dataFim: `${CURRENT_YEAR}-06-30`,
    createdAt: `${CURRENT_YEAR}-01-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-06-30T10:00:00Z`,
  },
  {
    id: 'proj-009',
    nome: 'H.I.D.R.A Core - RH/Financeiro',
    descricao: 'Ecossistema de dados centralizando bases das Diretorias Técnicas em repositório único com Apps Script, AppSheet, BigQuery, Looker Studio e IA preditiva.',
    categoria: 'tecnologia',
    status: 'planejamento',
    tipo: 'projeto',
    diretoria: 'Garantia / Fiança / Riscos',
    responsavel: 'NIE - Núcleo de Inteligência Estratégica',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-06-01`,
    createdAt: `${CURRENT_YEAR}-06-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-010',
    nome: 'Automação Axa - Envio Automático de NF e Folhas de Rosto',
    descricao: 'Robô que identifica e correlaciona Notas Fiscais e Folhas de Rosto, anexa arquivos corretos, envia para destinatários específicos e gera registro em PDF no Drive.',
    categoria: 'tecnologia',
    status: 'concluido',
    tipo: 'projeto',
    diretoria: 'Garantia / Fiança / Riscos',
    responsavel: 'Stephany Miara - Garantia',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-01-01`,
    dataFim: `${CURRENT_YEAR}-05-15`,
    createdAt: `${CURRENT_YEAR}-01-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-05-15T10:00:00Z`,
  },
  {
    id: 'proj-011',
    nome: 'Automação de Separação de Currículos',
    descricao: 'Automação de triagem e análise de currículos conforme requisitos de perfil, renomeando e salvando anexos automaticamente.',
    categoria: 'rh',
    status: 'concluido',
    tipo: 'projeto',
    diretoria: 'Garantia / Fiança / Riscos',
    responsavel: 'Stephany Miara - Garantia',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-02-01`,
    dataFim: `${CURRENT_YEAR}-04-30`,
    createdAt: `${CURRENT_YEAR}-02-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-04-30T10:00:00Z`,
  },
  {
    id: 'proj-012',
    nome: 'Addvalora News',
    descricao: 'Comunicado mensal sobre o mercado de Seguros contendo informações do mês, funcionando como jornal interno para manter a equipe informada.',
    categoria: 'marketing',
    status: 'ativo',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Geral (RCG)',
    responsavel: 'Luciana Hey',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-03-01`,
    createdAt: `${CURRENT_YEAR}-03-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-013',
    nome: 'DRL/SLA - Documentos e Prazos',
    descricao: 'Automação de triagem e controle de documentos com dinâmica de controle de prazo de acompanhamento dos gestores (80% concluído).',
    categoria: 'operacional',
    status: 'ativo',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Geral (RCG)',
    responsavel: 'Luciana Hey',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-04-01`,
    createdAt: `${CURRENT_YEAR}-04-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-014',
    nome: 'Alerta de Férias/Recessos',
    descricao: 'Robô que registra férias em planilha e envia avisos automáticos: 5 dias antes do início e 3 dias antes do retorno do colaborador.',
    categoria: 'rh',
    status: 'planejamento',
    tipo: 'projeto',
    diretoria: 'Garantia / Fiança / Riscos',
    responsavel: 'NIE - Núcleo de Inteligência Estratégica',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-08-01`,
    createdAt: `${CURRENT_YEAR}-08-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-015',
    nome: 'Addvalu - Geração de Vídeos com IA',
    descricao: 'Geração de vídeos personalizados com Inteligência Artificial para divulgação interna/externa, transformando textos e dados em conteúdos audiovisuais completos.',
    categoria: 'tecnologia',
    status: 'concluido',
    tipo: 'projeto',
    diretoria: 'Garantia / Fiança / Riscos',
    responsavel: 'NIE - Núcleo de Inteligência Estratégica',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-01-01`,
    dataFim: `${CURRENT_YEAR}-06-30`,
    createdAt: `${CURRENT_YEAR}-01-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-06-30T10:00:00Z`,
  },
  {
    id: 'proj-016',
    nome: 'Assistente Virtual Baruc',
    descricao: 'Assistente virtual com IA para auxiliar usuários do sistema Baruc via chat interativo, respondendo perguntas e guiando processos.',
    categoria: 'tecnologia',
    status: 'planejamento',
    tipo: 'projeto',
    diretoria: 'Garantia / Fiança / Riscos',
    responsavel: 'NIE - Núcleo de Inteligência Estratégica',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-09-01`,
    createdAt: `${CURRENT_YEAR}-09-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-017',
    nome: 'Alerta Google Drive e Email',
    descricao: 'Automação que envia notificações por e-mail para coordenadora sempre que houver alteração na planilha de férias/recesso.',
    categoria: 'tecnologia',
    status: 'planejamento',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Profissional (RCP)',
    responsavel: 'Viviane da Cruz - Administrativo',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-07-01`,
    createdAt: `${CURRENT_YEAR}-07-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-018',
    nome: 'Planilha de Controle de Agenda de Peritos',
    descricao: 'Planilha personalizada com automação de estimativa de valores orçamentários para organização de agenda e valores por perito.',
    categoria: 'operacional',
    status: 'concluido',
    tipo: 'projeto',
    diretoria: 'Property / Construção',
    responsavel: 'Rafael Hey',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-02-01`,
    dataFim: `${CURRENT_YEAR}-05-30`,
    createdAt: `${CURRENT_YEAR}-02-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-05-30T10:00:00Z`,
  },
  {
    id: 'proj-019',
    nome: 'Planilha RCV - AON',
    descricao: 'Planilha via Looker Studio para organização automática de informações e apresentação ao parceiro.',
    categoria: 'operacional',
    status: 'concluido',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Geral (RCG)',
    responsavel: 'Alex Guagliardi - RCG',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-01-15`,
    dataFim: `${CURRENT_YEAR}-04-15`,
    createdAt: `${CURRENT_YEAR}-01-15T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-04-15T10:00:00Z`,
  },
  {
    id: 'proj-020',
    nome: 'Addvalu - Vídeos para Clientes',
    descricao: 'Vídeos com IA para divulgação interna/externa explicando funcionalidades de robôs e sistemas (HDI, Avla, NotebookLm).',
    categoria: 'marketing',
    status: 'concluido',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Geral (RCG)',
    responsavel: 'William Fernandez',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-01-01`,
    dataFim: `${CURRENT_YEAR}-06-30`,
    createdAt: `${CURRENT_YEAR}-01-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-06-30T10:00:00Z`,
  },
  {
    id: 'proj-021',
    nome: 'Projeto Avla - BPO',
    descricao: 'Automação interna da caixa de distribuição de sinistros da Avla para otimização do fluxo de processos internos.',
    categoria: 'operacional',
    status: 'planejamento',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Geral (RCG)',
    responsavel: 'Avla Seguros S/A',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-10-01`,
    createdAt: `${CURRENT_YEAR}-10-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-022',
    nome: 'Assistente de Regulação',
    descricao: 'Vídeo com IA para apresentação de relatórios de sinistro, explicando o processo de regulação para Fairfax Seguros.',
    categoria: 'marketing',
    status: 'planejamento',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Geral (RCG)',
    responsavel: 'William Fernandez',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-08-01`,
    createdAt: `${CURRENT_YEAR}-08-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-023',
    nome: 'Addvalu - Espanha',
    descricao: 'Vídeo personalizado para a Matriz (Espanha) com divulgação global dos resultados do Grupo Addvalora.',
    categoria: 'marketing',
    status: 'concluido',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Geral (RCG)',
    responsavel: 'Francesc Llurba',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-03-01`,
    dataFim: `${CURRENT_YEAR}-05-30`,
    createdAt: `${CURRENT_YEAR}-03-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-05-30T10:00:00Z`,
  },
  {
    id: 'proj-024',
    nome: 'Painel de Resultados e Valores / Informe Semanal',
    descricao: 'Painel executivo para consolidação e visualização estratégica do faturamento interno por equipe, permitindo análise comparativa de performance.',
    categoria: 'financeiro',
    status: 'concluido',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Geral (RCG)',
    responsavel: 'William Fernandez',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-04-01`,
    dataFim: `${CURRENT_YEAR}-09-30`,
    createdAt: `${CURRENT_YEAR}-04-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-09-30T10:00:00Z`,
  },
  {
    id: 'proj-025',
    nome: 'Verificação Automática de Dados Financeiros',
    descricao: 'Automação de verificação e preenchimento de planilha para conferência de dados financeiros com ganho de agilidade.',
    categoria: 'financeiro',
    status: 'planejamento',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Profissional (RCP)',
    responsavel: 'Max - CFO Brasil',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-11-01`,
    createdAt: `${CURRENT_YEAR}-11-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-026',
    nome: 'Automação RCP',
    descricao: 'Automação do envio de comunicações aos reguladores no fluxo de RCP, com monitoramento automatizado de respostas.',
    categoria: 'operacional',
    status: 'planejamento',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Profissional (RCP)',
    responsavel: 'Everton - RCP Brasil',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-10-15`,
    createdAt: `${CURRENT_YEAR}-10-15T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-027',
    nome: 'Automação de Viagens e Deslocamentos',
    descricao: 'Workflow completo para solicitação de passagens, hotéis e locação de veículos com padronização e acompanhamento do fluxo.',
    categoria: 'operacional',
    status: 'planejamento',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Profissional (RCP)',
    responsavel: 'Max - CFO Brasil',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-12-01`,
    createdAt: `${CURRENT_YEAR}-12-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-029',
    nome: 'Sistema de Gestão de Sinistros Massificados',
    descricao: 'Desenvolvimento de plataforma para automação da regulação de sinistros de baixo valor e alta frequência.',
    categoria: 'operacional',
    status: 'ativo',
    tipo: 'projeto',
    diretoria: 'Property / Construção',
    responsavel: 'Paulo Cardoso - Property',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-05-01`,
    createdAt: `${CURRENT_YEAR}-05-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-030',
    nome: 'Portal do Corretor Addvalora',
    descricao: 'Interface exclusiva para corretores acompanharem o status de regulação e enviarem documentos de forma estruturada.',
    categoria: 'tecnologia',
    status: 'planejamento',
    tipo: 'projeto',
    diretoria: 'Garantia / Fiança / Riscos',
    responsavel: 'Equipe NIE',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-11-15`,
    createdAt: `${CURRENT_YEAR}-11-15T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-031',
    nome: 'Automação de Relatórios Mensais de Performance',
    descricao: 'Script para consolidação automática de KPIs de todas as diretorias em um dashboard executivo mensal.',
    categoria: 'financeiro',
    status: 'ativo',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Profissional (RCP)',
    responsavel: 'Max - CFO Brasil',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-04-01`,
    createdAt: `${CURRENT_YEAR}-04-01T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
  {
    id: 'proj-032',
    nome: 'Plataforma de Treinamento e Integração',
    descricao: 'Portal unificado para novos colaboradores acessarem materiais de treinamento e processos internos do Grupo.',
    categoria: 'rh',
    status: 'ativo',
    tipo: 'projeto',
    diretoria: 'Responsabilidade Civil Geral (RCG)',
    responsavel: 'Luciana Hey',
    link: '#',
    destaque: false,
    favorito: false,

    dataInicio: `${CURRENT_YEAR}-06-10`,
    createdAt: `${CURRENT_YEAR}-06-10T00:00:00Z`,
    updatedAt: `${CURRENT_YEAR}-12-20T10:00:00Z`,
  },
];

// ============================================
// DIRETORIAS - Atualizadas conforme imagem
// ============================================

export const DIRETORIAS = [
  'Property / Construção',
  'Property / Transportes / Mecânica / Elétrica',
  'Garantia / Fiança / Riscos',
  'Responsabilidade Civil Geral (RCG)',
  'Responsabilidade Civil Profissional (RCP)',
] as const;

// ============================================
// CATEGORY LABELS
// ============================================

export const CATEGORY_LABELS: Record<string, string> = {
  estrategia: 'Estratégia',
  operacional: 'Operacional',
  tecnologia: 'Tecnologia',
  financeiro: 'Financeiro',
  rh: 'Recursos Humanos',
  marketing: 'Marketing',
  juridico: 'Jurídico',
};

export const STATUS_LABELS: Record<string, string> = {
  ativo: 'Ativo',
  pausado: 'Pausado',
  concluido: 'Concluído',
  cancelado: 'Cancelado',
  planejamento: 'Em Planejamento',
};

export const PROFILE_LABELS: Record<string, string> = {
  master_admin: 'Master Admin',
  admin: 'Administrador',
  executivo: 'Executivo',
  diretoria: 'Diretoria',
  coordenacao: 'Coordenação',
  usuario_restrito: 'Usuário Restrito',
  usuario: 'Usuário',
};
